// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Museum.Persistence;

#nullable disable

namespace Museum.Persistence.Migrations
{
    [DbContext(typeof(MuseumTicketsDBContext))]
    [Migration("20260309192617_AddNewExhibitionsAndTickets")]
    partial class AddNewExhibitionsAndTickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Museum.Domain.Exhibition", b =>
                {
                    b.Property<int>("ExhibitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExhibitionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExhibitionId"), 10001L);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Photo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ExhibitionId");

                    b.ToTable("Exhibition");
                });

            modelBuilder.Entity("Museum.Domain.Museum", b =>
                {
                    b.Property<int>("MuseumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MuseumID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuseumId"), 10001L);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("MuseumComplexId")
                        .HasColumnType("int")
                        .HasColumnName("MuseumComplexID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MuseumId");

                    b.HasIndex("MuseumComplexId");

                    b.ToTable("Museum");
                });

            modelBuilder.Entity("Museum.Domain.MuseumComplex", b =>
                {
                    b.Property<int>("MuseumComplexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MuseumComplexID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuseumComplexId"), 10001L);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MuseumComplexId");

                    b.ToTable("MuseumComplex");
                });

            modelBuilder.Entity("Museum.Domain.MuseumExhibition", b =>
                {
                    b.Property<int>("MuseumExhibitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MuseumExhibitionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuseumExhibitionId"), 10001L);

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("ExhibitionId")
                        .HasColumnType("int")
                        .HasColumnName("ExhibitionID");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int")
                        .HasColumnName("MuseumID");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("MuseumExhibitionId");

                    b.HasIndex("ExhibitionId");

                    b.HasIndex("MuseumId");

                    b.ToTable("MuseumExhibition");
                });

            modelBuilder.Entity("Museum.Domain.MuseumSchedule", b =>
                {
                    b.Property<int>("MuseumScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MuseumScheduleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuseumScheduleId"), 10001L);

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int")
                        .HasColumnName("MuseumID");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("MuseumScheduleId");

                    b.HasIndex("MuseumId");

                    b.ToTable("MuseumSchedule");
                });

            modelBuilder.Entity("Museum.Domain.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 10001L);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Order", t =>
                        {
                            t.HasCheckConstraint("CHK_Order_Status", "[Status] IN (N'В ожидании', N'Оплачен', N'Отменён')");
                        });
                });

            modelBuilder.Entity("Museum.Domain.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"), 10001L);

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("money");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("TicketID");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("TicketId");

                    b.ToTable("OrderItem", t =>
                        {
                            t.HasCheckConstraint("CHK_OrderItem_Quantity", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("Museum.Domain.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"), 10001L);

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId");

                    b.ToTable("Payment", t =>
                        {
                            t.HasCheckConstraint("CHK_Payment_Amount", "[Amount] >= 0");
                        });
                });

            modelBuilder.Entity("Museum.Domain.ScheduleDay", b =>
                {
                    b.Property<int>("ScheduleDaysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScheduleDaysID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleDaysId"), 10001L);

                    b.Property<int>("MuseumScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("MuseumScheduleID");

                    b.Property<int>("WeekDay")
                        .HasColumnType("int");

                    b.HasKey("ScheduleDaysId");

                    b.HasIndex("MuseumScheduleId");

                    b.ToTable("ScheduleDays", t =>
                        {
                            t.HasCheckConstraint("CHK_ScheduleDays_WeekDay", "[WeekDay] BETWEEN 1 AND 7");
                        });
                });

            modelBuilder.Entity("Museum.Domain.ScheduleException", b =>
                {
                    b.Property<int>("ScheduleExceptionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScheduleExceptionsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleExceptionsId"), 10001L);

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("ExceptionDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<int>("MuseumScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("MuseumScheduleID");

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("time");

                    b.HasKey("ScheduleExceptionsId");

                    b.HasIndex("MuseumScheduleId");

                    b.ToTable("ScheduleExceptions");
                });

            modelBuilder.Entity("Museum.Domain.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TicketID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"), 10001L);

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ExhibitionId")
                        .HasColumnType("int")
                        .HasColumnName("ExhibitionID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TicketId");

                    b.HasIndex(new[] { "ExhibitionId", "Type" }, "UQ_Ticket_Exhibition_Type")
                        .IsUnique();

                    b.ToTable("Ticket", t =>
                        {
                            t.HasCheckConstraint("CHK_Ticket_Quantity", "[AvailableQuantity] >= 0");

                            t.HasCheckConstraint("CHK_Ticket_Status", "[Status] IN (N'Доступен', N'Продан', N'Отменён')");
                        });
                });

            modelBuilder.Entity("Museum.Domain.TicketPrice", b =>
                {
                    b.Property<int>("TicketPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TicketPriceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketPriceId"), 10001L);

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("TicketID");

                    b.HasKey("TicketPriceId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketPrice", t =>
                        {
                            t.HasCheckConstraint("CHK_TicketPrice_Price", "[Price] >= 0");
                        });
                });

            modelBuilder.Entity("Museum.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 10001L);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D10534D2118DAE")
                        .IsUnique();

                    b.ToTable("User", t =>
                        {
                            t.HasCheckConstraint("CHK_User_Role", "[Role] IN (N'Гость', N'Посетитель', N'Администратор музея', N'Администратор системы')");
                        });

                    b.HasData(
                        new
                        {
                            UserId = 10001,
                            Email = "admin@museum.ru",
                            FirstName = "Петр",
                            LastName = "Админов",
                            MiddleName = "Петрович",
                            Password = "$2a$11$0NR8Ir7eg9MNV9VFQsudROSeSoRodME7UsMzNNfmLla/e/gLzQyuK",
                            Phone = "+70000000000",
                            Role = "Администратор системы"
                        });
                });

            modelBuilder.Entity("Museum.Domain.Museum", b =>
                {
                    b.HasOne("Museum.Domain.MuseumComplex", "MuseumComplex")
                        .WithMany("Museums")
                        .HasForeignKey("MuseumComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuseumComplex");
                });

            modelBuilder.Entity("Museum.Domain.MuseumExhibition", b =>
                {
                    b.HasOne("Museum.Domain.Exhibition", "Exhibition")
                        .WithMany("MuseumExhibitions")
                        .HasForeignKey("ExhibitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Museum.Domain.Museum", "Museum")
                        .WithMany("MuseumExhibitions")
                        .HasForeignKey("MuseumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exhibition");

                    b.Navigation("Museum");
                });

            modelBuilder.Entity("Museum.Domain.MuseumSchedule", b =>
                {
                    b.HasOne("Museum.Domain.Museum", "Museum")
                        .WithMany("MuseumSchedules")
                        .HasForeignKey("MuseumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Museum");
                });

            modelBuilder.Entity("Museum.Domain.Order", b =>
                {
                    b.HasOne("Museum.Domain.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Museum.Domain.OrderItem", b =>
                {
                    b.HasOne("Museum.Domain.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Museum.Domain.Ticket", "Ticket")
                        .WithMany("OrderItems")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Museum.Domain.Payment", b =>
                {
                    b.HasOne("Museum.Domain.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Museum.Domain.ScheduleDay", b =>
                {
                    b.HasOne("Museum.Domain.MuseumSchedule", "MuseumSchedule")
                        .WithMany("ScheduleDays")
                        .HasForeignKey("MuseumScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuseumSchedule");
                });

            modelBuilder.Entity("Museum.Domain.ScheduleException", b =>
                {
                    b.HasOne("Museum.Domain.MuseumSchedule", "MuseumSchedule")
                        .WithMany("ScheduleExceptions")
                        .HasForeignKey("MuseumScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuseumSchedule");
                });

            modelBuilder.Entity("Museum.Domain.Ticket", b =>
                {
                    b.HasOne("Museum.Domain.Exhibition", "Exhibition")
                        .WithMany("Tickets")
                        .HasForeignKey("ExhibitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exhibition");
                });

            modelBuilder.Entity("Museum.Domain.TicketPrice", b =>
                {
                    b.HasOne("Museum.Domain.Ticket", "Ticket")
                        .WithMany("TicketPrices")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Museum.Domain.Exhibition", b =>
                {
                    b.Navigation("MuseumExhibitions");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Museum.Domain.Museum", b =>
                {
                    b.Navigation("MuseumExhibitions");

                    b.Navigation("MuseumSchedules");
                });

            modelBuilder.Entity("Museum.Domain.MuseumComplex", b =>
                {
                    b.Navigation("Museums");
                });

            modelBuilder.Entity("Museum.Domain.MuseumSchedule", b =>
                {
                    b.Navigation("ScheduleDays");

                    b.Navigation("ScheduleExceptions");
                });

            modelBuilder.Entity("Museum.Domain.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Museum.Domain.Ticket", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("TicketPrices");
                });

            modelBuilder.Entity("Museum.Domain.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
