// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Museum.Persistence;

#nullable disable

namespace Museum.Persistence.Migrations
{
    [DbContext(typeof(MuseumTicketsDBContext))]
    [Migration("20260302224120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Museum.Domain.Exhibition", b =>
                {
                    b.Property<int>("ExhibitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExhibitionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExhibitionId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Photo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ExhibitionId");

                    b.ToTable("Exhibition");

                    b.HasData(
                        new
                        {
                            ExhibitionId = 10001,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Шедевры Рембрандта",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10002,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Золото скифов",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10003,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Импрессионисты",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10004,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Искусство Востока",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10005,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Петровская эпоха",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10006,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "История гвардии",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10007,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Архитектура барокко",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10008,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Быт аристократии",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10009,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Фарфоровая сказка",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10010,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Техника росписи",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10011,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Русская икона",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10012,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Передвижники",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10013,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Авангард XX века",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10014,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Современное искусство",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10015,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Портретная галерея",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10016,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Скульптура Летнего сада",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10017,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Интерьеры Строгановых",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10018,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Тайны замка",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10019,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Дар меценатов",
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            ExhibitionId = 10020,
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Военная слава",
                            StartDate = new DateOnly(2024, 1, 1)
                        });
                });

            modelBuilder.Entity("Museum.Domain.Museum", b =>
                {
                    b.Property<int>("MuseumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MuseumID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuseumId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("MuseumComplexId")
                        .HasColumnType("int")
                        .HasColumnName("MuseumComplexID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MuseumId");

                    b.HasIndex("MuseumComplexId");

                    b.ToTable("Museum");

                    b.HasData(
                        new
                        {
                            MuseumId = 10001,
                            City = "Санкт-Петербург",
                            House = "34",
                            MuseumComplexId = 10001,
                            Name = "Зимний дворец",
                            Street = "Дворцовая наб."
                        },
                        new
                        {
                            MuseumId = 10002,
                            City = "Санкт-Петербург",
                            House = "6",
                            MuseumComplexId = 10001,
                            Name = "Главный штаб",
                            Street = "Дворцовая пл."
                        },
                        new
                        {
                            MuseumId = 10003,
                            City = "Санкт-Петербург",
                            House = "32",
                            MuseumComplexId = 10001,
                            Name = "Зимний дворец Петра I",
                            Street = "Дворцовая наб."
                        },
                        new
                        {
                            MuseumId = 10004,
                            City = "Санкт-Петербург",
                            House = "15",
                            MuseumComplexId = 10001,
                            Name = "Дворец Меншикова",
                            Street = "Университетская наб."
                        },
                        new
                        {
                            MuseumId = 10005,
                            City = "Санкт-Петербург",
                            House = "151",
                            MuseumComplexId = 10001,
                            Name = "Музей фарфора",
                            Street = "пр. Обуховской Обороны"
                        },
                        new
                        {
                            MuseumId = 10006,
                            City = "Санкт-Петербург",
                            House = "4",
                            MuseumComplexId = 10002,
                            Name = "Михайловский дворец",
                            Street = "Инженерная ул."
                        },
                        new
                        {
                            MuseumId = 10007,
                            City = "Санкт-Петербург",
                            House = "2",
                            MuseumComplexId = 10002,
                            Name = "Корпус Бенуа",
                            Street = "наб. канала Грибоедова"
                        },
                        new
                        {
                            MuseumId = 10008,
                            City = "Санкт-Петербург",
                            House = "5",
                            MuseumComplexId = 10002,
                            Name = "Мраморный дворец",
                            Street = "Миллионная ул."
                        },
                        new
                        {
                            MuseumId = 10009,
                            City = "Санкт-Петербург",
                            House = "17",
                            MuseumComplexId = 10002,
                            Name = "Строгановский дворец",
                            Street = "Невский пр."
                        },
                        new
                        {
                            MuseumId = 10010,
                            City = "Санкт-Петербург",
                            House = "2",
                            MuseumComplexId = 10002,
                            Name = "Михайловский замок",
                            Street = "Садовая ул."
                        });
                });

            modelBuilder.Entity("Museum.Domain.MuseumComplex", b =>
                {
                    b.Property<int>("MuseumComplexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MuseumComplexID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuseumComplexId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MuseumComplexId");

                    b.ToTable("MuseumComplex");

                    b.HasData(
                        new
                        {
                            MuseumComplexId = 10001,
                            Name = "Государственный Эрмитаж"
                        },
                        new
                        {
                            MuseumComplexId = 10002,
                            Name = "Государственный Русский музей"
                        });
                });

            modelBuilder.Entity("Museum.Domain.MuseumExhibition", b =>
                {
                    b.Property<int>("MuseumExhibitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MuseumExhibitionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuseumExhibitionId"));

                    b.Property<int>("ExhibitionId")
                        .HasColumnType("int")
                        .HasColumnName("ExhibitionID");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int")
                        .HasColumnName("MuseumID");

                    b.HasKey("MuseumExhibitionId");

                    b.HasIndex("ExhibitionId");

                    b.HasIndex("MuseumId");

                    b.ToTable("MuseumExhibition");
                });

            modelBuilder.Entity("Museum.Domain.MuseumSchedule", b =>
                {
                    b.Property<int>("MuseumScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MuseumScheduleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuseumScheduleId"));

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int")
                        .HasColumnName("MuseumID");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("MuseumScheduleId");

                    b.HasIndex("MuseumId");

                    b.ToTable("MuseumSchedule");
                });

            modelBuilder.Entity("Museum.Domain.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Museum.Domain.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("TicketID");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("TicketId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Museum.Domain.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Museum.Domain.ScheduleDay", b =>
                {
                    b.Property<int>("ScheduleDaysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScheduleDaysID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleDaysId"));

                    b.Property<int>("MuseumScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("MuseumScheduleID");

                    b.Property<int>("WeekDay")
                        .HasColumnType("int");

                    b.HasKey("ScheduleDaysId");

                    b.HasIndex("MuseumScheduleId");

                    b.ToTable("ScheduleDays");
                });

            modelBuilder.Entity("Museum.Domain.ScheduleException", b =>
                {
                    b.Property<int>("ScheduleExceptionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScheduleExceptionsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleExceptionsId"));

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("ExceptionDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<int>("MuseumScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("MuseumScheduleID");

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("time");

                    b.HasKey("ScheduleExceptionsId");

                    b.HasIndex("MuseumScheduleId");

                    b.ToTable("ScheduleExceptions");
                });

            modelBuilder.Entity("Museum.Domain.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TicketID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ExhibitionId")
                        .HasColumnType("int")
                        .HasColumnName("ExhibitionID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TicketId");

                    b.HasIndex(new[] { "ExhibitionId", "Type" }, "UQ_Ticket_Exhibition_Type")
                        .IsUnique();

                    b.ToTable("Ticket");

                    b.HasData(
                        new
                        {
                            TicketId = 10001,
                            AvailableQuantity = 100,
                            ExhibitionId = 10001,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10002,
                            AvailableQuantity = 50,
                            ExhibitionId = 10001,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10003,
                            AvailableQuantity = 100,
                            ExhibitionId = 10002,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10004,
                            AvailableQuantity = 50,
                            ExhibitionId = 10002,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10005,
                            AvailableQuantity = 100,
                            ExhibitionId = 10003,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10006,
                            AvailableQuantity = 50,
                            ExhibitionId = 10003,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10007,
                            AvailableQuantity = 100,
                            ExhibitionId = 10004,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10008,
                            AvailableQuantity = 50,
                            ExhibitionId = 10004,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10009,
                            AvailableQuantity = 100,
                            ExhibitionId = 10005,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10010,
                            AvailableQuantity = 50,
                            ExhibitionId = 10005,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10011,
                            AvailableQuantity = 100,
                            ExhibitionId = 10006,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10012,
                            AvailableQuantity = 50,
                            ExhibitionId = 10006,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10013,
                            AvailableQuantity = 100,
                            ExhibitionId = 10007,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10014,
                            AvailableQuantity = 50,
                            ExhibitionId = 10007,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10015,
                            AvailableQuantity = 100,
                            ExhibitionId = 10008,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10016,
                            AvailableQuantity = 50,
                            ExhibitionId = 10008,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10017,
                            AvailableQuantity = 100,
                            ExhibitionId = 10009,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10018,
                            AvailableQuantity = 50,
                            ExhibitionId = 10009,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10019,
                            AvailableQuantity = 100,
                            ExhibitionId = 10010,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10020,
                            AvailableQuantity = 50,
                            ExhibitionId = 10010,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10021,
                            AvailableQuantity = 100,
                            ExhibitionId = 10011,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10022,
                            AvailableQuantity = 50,
                            ExhibitionId = 10011,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10023,
                            AvailableQuantity = 100,
                            ExhibitionId = 10012,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10024,
                            AvailableQuantity = 50,
                            ExhibitionId = 10012,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10025,
                            AvailableQuantity = 100,
                            ExhibitionId = 10013,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10026,
                            AvailableQuantity = 50,
                            ExhibitionId = 10013,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10027,
                            AvailableQuantity = 100,
                            ExhibitionId = 10014,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10028,
                            AvailableQuantity = 50,
                            ExhibitionId = 10014,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10029,
                            AvailableQuantity = 100,
                            ExhibitionId = 10015,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10030,
                            AvailableQuantity = 50,
                            ExhibitionId = 10015,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10031,
                            AvailableQuantity = 100,
                            ExhibitionId = 10016,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10032,
                            AvailableQuantity = 50,
                            ExhibitionId = 10016,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10033,
                            AvailableQuantity = 100,
                            ExhibitionId = 10017,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10034,
                            AvailableQuantity = 50,
                            ExhibitionId = 10017,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10035,
                            AvailableQuantity = 100,
                            ExhibitionId = 10018,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10036,
                            AvailableQuantity = 50,
                            ExhibitionId = 10018,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10037,
                            AvailableQuantity = 100,
                            ExhibitionId = 10019,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10038,
                            AvailableQuantity = 50,
                            ExhibitionId = 10019,
                            Status = "Доступен",
                            Type = "Льготный"
                        },
                        new
                        {
                            TicketId = 10039,
                            AvailableQuantity = 100,
                            ExhibitionId = 10020,
                            Status = "Доступен",
                            Type = "Взрослый"
                        },
                        new
                        {
                            TicketId = 10040,
                            AvailableQuantity = 50,
                            ExhibitionId = 10020,
                            Status = "Доступен",
                            Type = "Льготный"
                        });
                });

            modelBuilder.Entity("Museum.Domain.TicketPrice", b =>
                {
                    b.Property<int>("TicketPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TicketPriceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketPriceId"));

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("TicketID");

                    b.HasKey("TicketPriceId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketPrice");

                    b.HasData(
                        new
                        {
                            TicketPriceId = 10001,
                            Price = 700.0m,
                            TicketId = 10001
                        },
                        new
                        {
                            TicketPriceId = 10002,
                            Price = 350.0m,
                            TicketId = 10002
                        },
                        new
                        {
                            TicketPriceId = 10003,
                            Price = 600.0m,
                            TicketId = 10003
                        },
                        new
                        {
                            TicketPriceId = 10004,
                            Price = 300.0m,
                            TicketId = 10004
                        },
                        new
                        {
                            TicketPriceId = 10005,
                            Price = 500.0m,
                            TicketId = 10005
                        },
                        new
                        {
                            TicketPriceId = 10006,
                            Price = 250.0m,
                            TicketId = 10006
                        },
                        new
                        {
                            TicketPriceId = 10007,
                            Price = 800.0m,
                            TicketId = 10007
                        },
                        new
                        {
                            TicketPriceId = 10008,
                            Price = 400.0m,
                            TicketId = 10008
                        },
                        new
                        {
                            TicketPriceId = 10009,
                            Price = 550.0m,
                            TicketId = 10009
                        },
                        new
                        {
                            TicketPriceId = 10010,
                            Price = 275.0m,
                            TicketId = 10010
                        },
                        new
                        {
                            TicketPriceId = 10011,
                            Price = 400.0m,
                            TicketId = 10011
                        },
                        new
                        {
                            TicketPriceId = 10012,
                            Price = 200.0m,
                            TicketId = 10012
                        },
                        new
                        {
                            TicketPriceId = 10013,
                            Price = 650.0m,
                            TicketId = 10013
                        },
                        new
                        {
                            TicketPriceId = 10014,
                            Price = 325.0m,
                            TicketId = 10014
                        },
                        new
                        {
                            TicketPriceId = 10015,
                            Price = 450.0m,
                            TicketId = 10015
                        },
                        new
                        {
                            TicketPriceId = 10016,
                            Price = 225.0m,
                            TicketId = 10016
                        },
                        new
                        {
                            TicketPriceId = 10017,
                            Price = 300.0m,
                            TicketId = 10017
                        },
                        new
                        {
                            TicketPriceId = 10018,
                            Price = 150.0m,
                            TicketId = 10018
                        },
                        new
                        {
                            TicketPriceId = 10019,
                            Price = 250.0m,
                            TicketId = 10019
                        },
                        new
                        {
                            TicketPriceId = 10020,
                            Price = 125.0m,
                            TicketId = 10020
                        },
                        new
                        {
                            TicketPriceId = 10021,
                            Price = 500.0m,
                            TicketId = 10021
                        },
                        new
                        {
                            TicketPriceId = 10022,
                            Price = 250.0m,
                            TicketId = 10022
                        },
                        new
                        {
                            TicketPriceId = 10023,
                            Price = 600.0m,
                            TicketId = 10023
                        },
                        new
                        {
                            TicketPriceId = 10024,
                            Price = 300.0m,
                            TicketId = 10024
                        },
                        new
                        {
                            TicketPriceId = 10025,
                            Price = 750.0m,
                            TicketId = 10025
                        },
                        new
                        {
                            TicketPriceId = 10026,
                            Price = 375.0m,
                            TicketId = 10026
                        },
                        new
                        {
                            TicketPriceId = 10027,
                            Price = 400.0m,
                            TicketId = 10027
                        },
                        new
                        {
                            TicketPriceId = 10028,
                            Price = 200.0m,
                            TicketId = 10028
                        },
                        new
                        {
                            TicketPriceId = 10029,
                            Price = 350.0m,
                            TicketId = 10029
                        },
                        new
                        {
                            TicketPriceId = 10030,
                            Price = 175.0m,
                            TicketId = 10030
                        },
                        new
                        {
                            TicketPriceId = 10031,
                            Price = 450.0m,
                            TicketId = 10031
                        },
                        new
                        {
                            TicketPriceId = 10032,
                            Price = 225.0m,
                            TicketId = 10032
                        },
                        new
                        {
                            TicketPriceId = 10033,
                            Price = 550.0m,
                            TicketId = 10033
                        },
                        new
                        {
                            TicketPriceId = 10034,
                            Price = 275.0m,
                            TicketId = 10034
                        },
                        new
                        {
                            TicketPriceId = 10035,
                            Price = 650.0m,
                            TicketId = 10035
                        },
                        new
                        {
                            TicketPriceId = 10036,
                            Price = 325.0m,
                            TicketId = 10036
                        },
                        new
                        {
                            TicketPriceId = 10037,
                            Price = 400.0m,
                            TicketId = 10037
                        },
                        new
                        {
                            TicketPriceId = 10038,
                            Price = 200.0m,
                            TicketId = 10038
                        },
                        new
                        {
                            TicketPriceId = 10039,
                            Price = 500.0m,
                            TicketId = 10039
                        },
                        new
                        {
                            TicketPriceId = 10040,
                            Price = 250.0m,
                            TicketId = 10040
                        });
                });

            modelBuilder.Entity("Museum.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D10534D2118DAE")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 10001,
                            Email = "admin@museum.ru",
                            FirstName = "Петр",
                            LastName = "Админов",
                            MiddleName = "Петрович",
                            Password = "$2a$11$0NR8Ir7eg9MNV9VFQsudROSeSoRodME7UsMzNNfmLla/e/gLzQyuK",
                            Phone = "+70000000000",
                            Role = "Администратор системы"
                        });
                });

            modelBuilder.Entity("Museum.Domain.Museum", b =>
                {
                    b.HasOne("Museum.Domain.MuseumComplex", "MuseumComplex")
                        .WithMany("Museums")
                        .HasForeignKey("MuseumComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuseumComplex");
                });

            modelBuilder.Entity("Museum.Domain.MuseumExhibition", b =>
                {
                    b.HasOne("Museum.Domain.Exhibition", "Exhibition")
                        .WithMany("MuseumExhibitions")
                        .HasForeignKey("ExhibitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Museum.Domain.Museum", "Museum")
                        .WithMany("MuseumExhibitions")
                        .HasForeignKey("MuseumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exhibition");

                    b.Navigation("Museum");
                });

            modelBuilder.Entity("Museum.Domain.MuseumSchedule", b =>
                {
                    b.HasOne("Museum.Domain.Museum", "Museum")
                        .WithMany("MuseumSchedules")
                        .HasForeignKey("MuseumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Museum");
                });

            modelBuilder.Entity("Museum.Domain.Order", b =>
                {
                    b.HasOne("Museum.Domain.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Museum.Domain.OrderItem", b =>
                {
                    b.HasOne("Museum.Domain.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Museum.Domain.Ticket", "Ticket")
                        .WithMany("OrderItems")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Museum.Domain.Payment", b =>
                {
                    b.HasOne("Museum.Domain.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Museum.Domain.ScheduleDay", b =>
                {
                    b.HasOne("Museum.Domain.MuseumSchedule", "MuseumSchedule")
                        .WithMany("ScheduleDays")
                        .HasForeignKey("MuseumScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuseumSchedule");
                });

            modelBuilder.Entity("Museum.Domain.ScheduleException", b =>
                {
                    b.HasOne("Museum.Domain.MuseumSchedule", "MuseumSchedule")
                        .WithMany("ScheduleExceptions")
                        .HasForeignKey("MuseumScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuseumSchedule");
                });

            modelBuilder.Entity("Museum.Domain.Ticket", b =>
                {
                    b.HasOne("Museum.Domain.Exhibition", "Exhibition")
                        .WithMany("Tickets")
                        .HasForeignKey("ExhibitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exhibition");
                });

            modelBuilder.Entity("Museum.Domain.TicketPrice", b =>
                {
                    b.HasOne("Museum.Domain.Ticket", "Ticket")
                        .WithMany("TicketPrices")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Museum.Domain.Exhibition", b =>
                {
                    b.Navigation("MuseumExhibitions");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Museum.Domain.Museum", b =>
                {
                    b.Navigation("MuseumExhibitions");

                    b.Navigation("MuseumSchedules");
                });

            modelBuilder.Entity("Museum.Domain.MuseumComplex", b =>
                {
                    b.Navigation("Museums");
                });

            modelBuilder.Entity("Museum.Domain.MuseumSchedule", b =>
                {
                    b.Navigation("ScheduleDays");

                    b.Navigation("ScheduleExceptions");
                });

            modelBuilder.Entity("Museum.Domain.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Museum.Domain.Ticket", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("TicketPrices");
                });

            modelBuilder.Entity("Museum.Domain.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
